services:
    app:
        platform: linux/x86_64
        build: .
        ports:
            - 3000:3000
            - 3001:3001
        image: andrew2021wang/image:latest

volumes:
    mongo_db: {}
